### ISSUE TITLE
Invalid path alias

### ISSUE THREAD

**Issue by yafater** [mitrm/yii2-amcharts#1]
hello and thanks a lot for this extension.
I used this extentsion but I offer to change this line of your code 
    public $sourcePath = '@/mitrm/yii2-amcharts/assets';

to
    public $sourcePath = '@vendor/mitrm/yii2-amcharts/assets';
for this error
Invalid path alias: @mitrm/yii2-amcharts/assets

**Comment by mitrm** [comment]
ok
