### ISSUE TITLE
theme configuration

### ISSUE THREAD

**Issue by yafater** [mitrm/yii2-amcharts#2]
Hello again.
by adding theme in configuration any changes don't apply.

I think it has a problem?
 public function addThemeJs($theme)
    {
        $this->js[] = 'themes/' . $theme . '.js';
    }

may be a change like this:
    public function addThemeJs($theme)
    {
        $this->js[] = 'amcharts/themes/' . $theme . '.js';
    }

**Comment by mitrm** [comment]
ok
